name: release

on:
  push:
    branches:
      - stable

jobs:
  pypi-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: {{ cookiecutter.python_version }}

      - name: Install Poetry
        run: |
          make get-poetry
          echo $HOME/.poetry/bin >> $GITHUB_PATH

      # Cache the .venv directory
      - name: Set up Poetry cache
        uses: actions/cache@v2
        id: poetry-cache
        with:
          key: {% raw %}poetry-cache-${{ hashFiles('**/poetry.lock') }}{% endraw %}
          path: .venv

      - name: Install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Build the package
        run: poetry build

      - name: Publish the package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: {% raw %}${{ secrets.PYPI_API_TOKEN }}{% endraw %}

  github-release:
    needs: pypi-release

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: {{ cookiecutter.python_version }}

      - name: Install Poetry
        run: |
          make get-poetry
          echo $HOME/.poetry/bin >> $GITHUB_PATH

      # Cache the .venv directory
      - name: Set up Poetry cache
        uses: actions/cache@v2
        id: poetry-cache
        with:
          key: {% raw %}poetry-cache-${{ hashFiles('**/poetry.lock') }}{% endraw %}
          path: .venv

      - name: Install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Get version
        id: version
        run: echo ::set-output name=version::$(poetry version | rev | cut -d' ' -f1 | rev)

      - name: Get Pull Request data
        uses: jwalton/gh-find-current-pr@v1
        id: find-pr
        with:
          state: all

      - name: Tag and Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: {% raw %}${{ steps.version.outputs.version }}{% endraw %}
          name: {% raw %}${{ steps.version.outputs.version }}{% endraw %}
          body: |
            {% raw %}${{ steps.find-pr.outputs.body }}{% endraw %}
          draft: false
          prerelease: false
